@echo off
rem Purpose: Process an input string using MeCab and format it in Wakati.
rem Tools: MeCab
rem Usage: file.bat <input_string>

setlocal EnableDelayedExpansion

rem Set the code page to UTF-8 for proper character encoding
chcp 65001 > nul

rem Replace \n with a space in the input string to avoid issues
set "input_string=%*"
set "input_string=!input_string:\n= !"

rem Write the input string to a temporary file
echo !input_string! > "input.txt"

rem Run MeCab with the input string
rem Ensure the path below points to your MeCab dictionary
mecab -d "C:\Users\User\Download\yomichan\unidic-cwj-202302" "input.txt" -o "out.txt" -O wakati

rem Check if the MeCab output file exists
if exist "out.txt" (
    rem Display the output generated by MeCab
    type "out.txt"
) else (
    echo MeCab output file not found.
)

rem Clean up temporary files
del "input.txt" >nul 2>&1
del "out.txt" >nul 2>&1

endlocal